### ISSUE TITLE
problem with ibm bluemix

### ISSUE THREAD

**Issue by axxg** [cloudfoundry-community/etherpad-lite-cf#4]
I get the following message:

> cf push xxxx -m 512M
> Updating app xxxx

OK

Uploading xxxx...
Uploading app files from: xxxx
Uploading 2M, 367 files
Done uploading
OK

Stopping app xxxx

OK

Starting app xxxx

-----> Downloaded app package (1.1M)
-----> Downloaded app buildpack cache (22M)
    Staging failed: An application could not be detected by any available buildpack

FAILED
NoAppDetectedError

What should I do?

**Comment by axxg** [comment]
I fixed the first problem, but now i get:

UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
TypeError: pad.collabClient is null in http://XXXXXXXX.mybluemix.net/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'

UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
Uncaught TypeError: Cannot read property 'setChannelState' of null in http://xxxxxxx.mybluemix.net/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'

**Comment by ArthurHlt** [comment]
Sorry for the long time I took for answer, I actually change few things for building etherpad-lite. You can try with this version and let me know

**Comment by ArthurHlt** [comment]
I have no answer from the original author, I consider this as fixed and close this issue.
