### ISSUE TITLE
Upgrade to 1.6.1 upstream release

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-community/etherpad-lite-cf#9]
Upstream upgrade procedure is documented at https://github.com/cloudfoundry-community/etherpad-lite-cf/blob/cloudfoundry/UPDATE.md

Unsuccessfully tried merging upstream 1.6.1 with previous node7 upgrade from @poblin-orange in [update_1_6_1](https://github.com/cloudfoundry-community/etherpad-lite-cf/compare/cloudfoundry...cloudfoundry-community:update_1_6_1?expand=1) branch.

Failed in https://travis-ci.org/cloudfoundry-community/etherpad-lite-cf/builds/263540878 with

> $ mv node_modules/ep_etherpad-lite/node_modules/ep_* node_modules
> mv: cannot stat `node_modules/ep_etherpad-lite/node_modules/ep_*': No such file or directory

Would need local building and checking upstream changes. 
Moving this into a distinct issue

**Comment by gberche-orange** [comment]
Made a mistake when handling merge conflict in 3f02e4c1e381a50a25c02785f3ec2535b7c380f4 where I removed by mistake the ep_ modules from package.json. Need to reapply properly steps documented at  https://github.com/cloudfoundry-community/etherpad-lite-cf/blob/cloudfoundry/UPDATE.md

**Comment by gberche-orange** [comment]
Re-performed the update procedure to 1.6.1 into 9d0f5e968cfc60e2566e498d29044bfee58cd35d and https://github.com/cloudfoundry-community/etherpad-lite-cf/releases/tag/1.6.1-cf

Now hitting https://github.com/ether/etherpad-lite/issues/3117, this could be related to https://github.com/ether/etherpad-lite/pull/3084 trying to fix https://github.com/ether/etherpad-lite/issues/3074.

Next steps:
* [x] try to update to latest commits in upstream master. Failed with same symptoms, see [traces](https://gist.github.com/gberche-orange/8be6f200bdc1d1d9b30d538125f951f7)
   * [x] try running with latest nodejs 6.9.x version instead of nodejs 7. Failed with same symtoms, see [traces](https://gist.github.com/gberche-orange/877fa71d19c1d8a321b8b3447b4686eb)
   * [ ] try *building* and running with latest nodejs 6.9.x version instead of nodejs 7
      * [x] try reverting https://github.com/ether/etherpad-lite/pull/3084. Built in 1.6.1-cf-a0aedd679301e5bb75cedf889f91e89e8e5014b7-node69 Failed with infinite recursion (see [traces](https://gist.github.com/gberche-orange/0796db0ffd58b5491f8cd9583034b9a2))
* [x] try to stick with etherpad-lite-1.6.0 with node js 6.9.x. Tried in 1.6.0-cf-node169 tag. Now displaying new [error traces](https://gist.github.com/gberche-orange/0cce826474dda597b86c8e6dd1352bc3#file-etherpad-lite-cf-160-node-69-txt-L90-L91), along with internal mysql infrastructure issues. 
* [ ] Dig into https://github.com/ether/etherpad-lite/pull/3084 to understand if etherpad-lite-cf specifics would be interferring such as https://github.com/cloudfoundry-community/etherpad-lite-cf/blob/1.6.0-cf-node169/.travis.yml#L9-L12 Possibly getting help from @ArthurHlt

**Comment by wayglem** [comment]
The new release etherpad-lite-cf-1.6.3 supports Node8 which is the LTS version.
